- name: Copy bash script to server
  copy:
    src: install.sh
    dest: /opt/install-kubectl.sh
    mode: '0777'

- name: execute bash script on server
  shell: bash /opt/install-kubectl.sh

- name: Installing Skaffold
  shell: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/