- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes
- name: Install OpenJDK Java
  become: yes
  apt:
    name: [gnupg, gnupg2, gnupg1, default-jre, default-jdk]
    state: present
- name: download jenkins bin
  shell: wget -qO - https://pkg.jenkins.io/debian-stable/jenkins.io.key | sudo apt-key add -
- name: run the bin file
  shell: sudo sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
- name: Update APT package manager repositories cache
  become: true
  apt:
    update_cache: yes
- name : install jenkins
  become: yes
  apt:
    name: jenkins
    state: present
- name: start and enable jenkins server
  become: yes
  service:
    name: jenkins
    state: started