- name: Ensure Java is installed (Amazon Linux 2)
  yum:
    name: java-17-amazon-corretto
    state: present
  become: true

- name: Add Jenkins repo
  get_url:
    url: http://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Import Jenkins GPG key
  rpm_key:
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    state: present
  become: true

- name: Install Jenkins
  yum:
    name: jenkins
    state: present
  become: true

- name: Enable and start Jenkins service
  systemd:
    name: jenkins
    enabled: true
    state: started
  become: true